<option value="Access Bank">Access Bank</option>
<option value="Citi Bank">Citi Bank</option>
<option value="Coronation Merchant Bank">Coronation Merchant Bank</option>
<option value="EcoBank">EcoBank</option>
<option value="FBNQUEST Merchant Bank">FBNQUEST Merchant Bank</option>
<option value="Fidelity Bank">Fidelity Bank</option>
<option value="First Bank of Nigeria">First Bank of Nigeria</option>
<option value="First City Monument Bank (FCMB)">First City Monument Bank (FCMB)</option>
<option value="FSDH Merchant Bank">FSDH Merchant Bank</option>
<option value="Globus Bank">Globus Bank</option>
<option value="Greenwich Merchant Bank">Greenwich Merchant Bank</option>
<option value="Guarantee Trust Bank (GTB)">Guarantee Trust Bank (GTB)</option>
<option value="Heritage Bank">Heritage Bank</option>
<option value="Jaiz Bank">Jaiz Bank</option>
<option value="Keystone Bank">Keystone Bank</option>
<option value="Lotus Bank">Lotus Bank</option>
<option value="Nova Merchant Bank">Nova Merchant Bank</option>
<option value="Polaris Bank">Polaris Bank</option>
<option value="Providus Bank">Providus Bank</option>
<option value="Rand Merchant Bank">Rand Merchant Bank</option>
<option value="Stanbic IBTC Bank">Stanbic IBTC Bank</option>
<option value="Standard Chartered Bank">Standard Chartered Bank</option>
<option value="Sterling Bank">Sterling Bank</option>
<option value="Suntrust Bank">Suntrust Bank</option>
<option value="Taj Bank">Taj Bank</option>
<option value="Titan Trust Bank">Titan Trust Bank</option>
<option value="Union Bank Plc">Union Bank Plc</option>
<option value="United Bank for Africa (UBA)">United Bank for Africa (UBA)</option>
<option value="Unity Bank">Unity Bank</option>
<option value="Wema Bank">Wema Bank</option>
<option value="Zenith Bank">Zenith Bank</option>
